/**
 * OpenClaw Adapter Contract Tests
 *
 * Investigation conclusion (August 2026):
 *   The "Cannot read properties of undefined (reading 'id')" crash in the
 *   Chief of Staff → Operations Manager task was NOT caused by the OpenClaw
 *   update. Evidence:
 *
 *   1. The CoS → OM standard execution path (dispatchWorkExecution →
 *      workExecutionPipelineService.executeWork) does NOT call
 *      engine.submitExecution() — it uses the AI gateway (OpenAI / rule-based).
 *      OpenClaw is only invoked via the separate POST /tasks/:id/submit route.
 *
 *   2. openClawExecutionEngine.submitExecution accesses brokerResponse.status,
 *      brokerResponse.reason, brokerResponse.runtimeExecutionId, and
 *      brokerResponse.estimatedStartAt. There is no .id access on the broker
 *      response object.
 *
 *   3. The recent OpenClaw updates (commits 841ec7e and caa0ae3) changed
 *      LiveGatewayAdapter internals and added cross-platform adapters in the
 *      Electron app. Neither commit changed:
 *        - executions.ts (the broker route that forms the HTTP response)
 *        - OpenClawSubmissionResponse (unchanged type)
 *        - OpenClawWebhookEvent (unchanged type)
 *        - BrokerWebhookEvent.eventId (still generated by randomUUID on the broker)
 *
 *   4. The actual crash was the addMessage/SSE handler bug (return msg! silently
 *      returned undefined when DB RETURNING yielded 0 rows), fixed in
 *      regression-undefined-agent-message.test.ts.
 *
 * These tests lock down the OpenClaw adapter contract so any future
 * OpenClaw update that drifts the response shape is caught before production.
 */

import { describe, it, expect, vi, beforeEach } from "vitest";
import { OpenClawExecutionEngine, RuntimeBrokerClient } from "@workspace/openclaw";
import type { ExecutionPackage } from "@workspace/agent-runtime";

// ─── DB mock — vi.hoisted() required so factory closures can reference these ─

const { mockDbInsert, mockDbUpdate, mockDbSelect } = vi.hoisted(() => {
  const mockDbInsert = vi.fn().mockReturnValue({
    values: vi.fn().mockReturnValue({
      onConflictDoNothing: vi.fn().mockResolvedValue(undefined),
    }),
  });
  const mockDbUpdate = vi.fn().mockReturnValue({
    set: vi.fn().mockReturnValue({ where: vi.fn().mockResolvedValue(undefined) }),
  });
  const mockDbSelect = vi.fn().mockReturnValue({
    from:  vi.fn().mockReturnThis(),
    where: vi.fn().mockReturnThis(),
    limit: vi.fn().mockResolvedValue([]),
  });
  return { mockDbInsert, mockDbUpdate, mockDbSelect };
});

vi.mock("@workspace/db", () => ({
  db: {
    insert: (...a: unknown[]) => mockDbInsert(...a),
    update: (...a: unknown[]) => mockDbUpdate(...a),
    select: (...a: unknown[]) => mockDbSelect(...a),
  },
  executionSessionsTable: { id: "id" },
  executionEventsTable:   { id: "id" },
  tasksTable:             { id: "id" },
}));

vi.mock("drizzle-orm", () => ({
  eq:      (a: unknown, b: unknown) => ({ op: "eq", a, b }),
  and:     (...args: unknown[]) => ({ op: "and", args }),
  desc:    (a: unknown) => ({ op: "desc", a }),
  inArray: (a: unknown, b: unknown) => ({ op: "inArray", a, b }),
}));

// ─── Test config and package helpers ─────────────────────────────────────────

const MOCK_CONFIG = {
  runtimeUrl:           "http://localhost:19002",
  authTokenRef:         null,
  webhookSecret:        null,
  retryAttempts:        0,
  retryDelayMs:         0,
  timeoutMs:            5000,
  heartbeatIntervalMs:  60000,
  executionTtlSeconds:  300,
  callbackBaseUrl:      "http://localhost:8080",
};

function makePackage(overrides: Partial<ExecutionPackage> = {}): ExecutionPackage {
  return {
    executionId:    "exec-contract-1",
    taskId:         "task-1",
    tenantId:       "org-1",
    workforceRole:  "chief_of_staff",
    specialistManifest: {
      specialistId:        "cos",
      workforceRole:       "chief_of_staff",
      displayName:         "Chief of Staff",
      domain:              "Strategy",
      dnaProfileId:        "chief_of_staff",
      dnaVersion:          "1.0.0",
      manifestVersion:     1,
      manifestHash:        "abc",
      mission:             "Lead strategic coordination.",
      objectives:          ["Ensure strategic alignment"],
      responsibilities:    ["Coordinate", "Review"],
      operatingPrinciples: ["Integrity"],
      communicationStyle: { tone: "executive", detailLevel: "formal", language: "English" },
      competencies:        [],
      escalationRules:     [],
      prohibitedBehaviours: [],
      memoryPolicy:        { allowedScopes: ["task_context"], retentionPolicy: "session_only" },
      resourceRequirements: [],
    } as any,
    runtimeInstructions: {
      instruction:     "You are the CoS",
      instructionHash: "deadbeef",
      manifestHash:    "abc",
      dnaVersion:      "1.0.0",
      specialistId:    "cos",
      compiledAt:      new Date().toISOString(),
    },
    workerProfile: {
      allowedChannels:              ["api"],
      allowedBrowserDomains:        [],
      allowedLocalPathCategories:   [],
      allowedApplicationCategories: [],
      prohibitedActions:            [],
      riskLevel:                    "low",
      requiresApprovalFor:          [],
    },
    steps: [{
      sequence:         1,
      specialist:       "chief_of_staff",
      action:           "execute",
      description:      "Do work",
      requiresApproval: false,
    }],
    requestedTools:               ["api_call"],
    requestedChannels:            ["api"],
    requestedConnectorCategories: [],
    approvalState:                "not_required",
    constraints: {
      maxDurationSeconds:               300,
      requireHumanApprovalBeforeSubmit: false,
      allowedDataCategories:            ["task_context"],
    },
    callbackUrl: "http://localhost:8080/v1/runtime/events",
    expiresAt:   new Date(Date.now() + 300_000).toISOString(),
    issuedAt:    new Date().toISOString(),
    ...overrides,
  } as ExecutionPackage;
}

// Spy on the broker client's submitExecution method so we can control what
// the "broker HTTP response" looks like without starting an actual server.
// startHeartbeat() is called explicitly (not by the constructor), so no
// heartbeat spy is needed when we call new OpenClawExecutionEngine(config)
// directly in tests.
let submitSpy: ReturnType<typeof vi.spyOn>;

beforeEach(() => {
  vi.clearAllMocks();
  submitSpy = vi.spyOn(RuntimeBrokerClient.prototype, "submitExecution");
});

// ─── Contract: valid responses ────────────────────────────────────────────────

describe("OpenClaw adapter contract — valid broker responses", () => {
  it("accepted response — returns accepted outcome with runtimeExecutionId", async () => {
    submitSpy.mockResolvedValue({
      runtimeExecutionId: "runtime-exec-abc",
      status:             "accepted",
      runtimeVersion:     "1.0.0",
    });

    const engine = new OpenClawExecutionEngine(MOCK_CONFIG as any);
    const result = await engine.submitExecution(makePackage());

    expect(result.outcome).toBe("accepted");
    expect(result.runtimeExecutionId).toBe("runtime-exec-abc");
  });

  it("queued response — returns queued outcome with estimatedStartAt", async () => {
    const eta = new Date(Date.now() + 5000).toISOString();
    submitSpy.mockResolvedValue({
      runtimeExecutionId: "runtime-exec-queued",
      status:             "queued",
      runtimeVersion:     "1.0.0",
      estimatedStartAt:   eta,
    });

    const engine = new OpenClawExecutionEngine(MOCK_CONFIG as any);
    const result = await engine.submitExecution(makePackage());

    expect(result.outcome).toBe("queued");
    expect(result.runtimeExecutionId).toBe("runtime-exec-queued");
    expect(result.estimatedStartAt).toBe(eta);
  });

  it("rejected response — returns rejected outcome with reason, null runtimeExecutionId", async () => {
    submitSpy.mockResolvedValue({
      runtimeExecutionId: "",
      status:             "rejected",
      reason:             "Tenant not authorised",
      runtimeVersion:     "1.0.0",
    });

    const engine = new OpenClawExecutionEngine(MOCK_CONFIG as any);
    const result = await engine.submitExecution(makePackage());

    expect(result.outcome).toBe("rejected");
    expect(result.runtimeExecutionId).toBeNull();
    expect(result.rejectionReason).toBe("Tenant not authorised");
  });

  it("backward compat — runtimeVersion omitted: succeeds (optional field)", async () => {
    submitSpy.mockResolvedValue({
      runtimeExecutionId: "runtime-exec-no-ver",
      status:             "accepted",
      // runtimeVersion deliberately omitted
    });

    const engine = new OpenClawExecutionEngine(MOCK_CONFIG as any);
    const result = await engine.submitExecution(makePackage());

    expect(result.outcome).toBe("accepted");
    expect(result.runtimeExecutionId).toBe("runtime-exec-no-ver");
  });
});

// ─── Contract drift: malformed broker responses ───────────────────────────────

describe("OpenClaw adapter contract — MALFORMED_BROKER_RESPONSE guard", () => {
  it("missing runtimeExecutionId on accepted: throws MALFORMED_BROKER_RESPONSE", async () => {
    // Simulates an OpenClaw update that renamed runtimeExecutionId → id.
    // The guard must catch this BEFORE the engine reads .runtimeExecutionId
    // and silently gets undefined, which then crashes downstream as
    // "Cannot read properties of undefined (reading 'id')".
    submitSpy.mockResolvedValue({
      id:             "runtime-exec-new-field", // field renamed — runtimeExecutionId absent
      status:         "accepted",
      runtimeVersion: "2.0.0",
    });

    const engine = new OpenClawExecutionEngine(MOCK_CONFIG as any);
    const err = await engine.submitExecution(makePackage()).catch(e => e);

    expect(err).toBeInstanceOf(Error);
    expect((err as { code?: string }).code).toBe("MALFORMED_BROKER_RESPONSE");
    expect((err as Error).message).toMatch(/runtimeExecutionId/);
  });

  it("unknown status value ('success'): throws MALFORMED_BROKER_RESPONSE", async () => {
    // Simulates an update that changed the status enum (accepted → success).
    submitSpy.mockResolvedValue({
      runtimeExecutionId: "runtime-exec-1",
      status:             "success",       // not in the accepted enum
      runtimeVersion:     "2.0.0",
    });

    const engine = new OpenClawExecutionEngine(MOCK_CONFIG as any);
    const err = await engine.submitExecution(makePackage()).catch(e => e);

    expect(err).toBeInstanceOf(Error);
    expect((err as { code?: string }).code).toBe("MALFORMED_BROKER_RESPONSE");
    expect((err as Error).message).toMatch(/unknown status/);
  });

  it("response wrapped in data envelope: throws MALFORMED_BROKER_RESPONSE", async () => {
    // Simulates an update that wrapped the response: { data: {...}, meta: {...} }
    submitSpy.mockResolvedValue({
      data: {
        runtimeExecutionId: "runtime-exec-1",
        status:             "accepted",
        runtimeVersion:     "2.0.0",
      },
      meta: { requestId: "req-1" },
    });

    const engine = new OpenClawExecutionEngine(MOCK_CONFIG as any);
    const err = await engine.submitExecution(makePackage()).catch(e => e);

    expect(err).toBeInstanceOf(Error);
    expect((err as { code?: string }).code).toBe("MALFORMED_BROKER_RESPONSE");
  });

  it("null response: throws MALFORMED_BROKER_RESPONSE (not TypeError at .id)", async () => {
    // The addMessage bug class applied to the broker: if submitExecution returns
    // null/undefined, the engine must throw explicitly rather than propagating
    // undefined to callers that then crash at .runtimeExecutionId or .id.
    submitSpy.mockResolvedValue(null);

    const engine = new OpenClawExecutionEngine(MOCK_CONFIG as any);
    const err = await engine.submitExecution(makePackage()).catch(e => e);

    expect(err).toBeInstanceOf(Error);
    expect((err as { code?: string }).code).toBe("MALFORMED_BROKER_RESPONSE");
  });

  it("undefined response: throws MALFORMED_BROKER_RESPONSE", async () => {
    submitSpy.mockResolvedValue(undefined as any);

    const engine = new OpenClawExecutionEngine(MOCK_CONFIG as any);
    const err = await engine.submitExecution(makePackage()).catch(e => e);

    expect(err).toBeInstanceOf(Error);
    expect((err as { code?: string }).code).toBe("MALFORMED_BROKER_RESPONSE");
  });
});

// ─── Field-name assumptions ───────────────────────────────────────────────────

describe("OpenClaw adapter contract — response field name assumptions", () => {
  const INVALID_ID_VARIANTS = [
    { id:              "exec-1", status: "accepted", runtimeVersion: "1.0.0" },
    { run:             { id: "exec-1" }, status: "accepted", runtimeVersion: "1.0.0" },
    { job:             { id: "exec-1" }, status: "accepted", runtimeVersion: "1.0.0" },
    { data:            { runtimeExecutionId: "exec-1" }, status: "accepted", runtimeVersion: "1.0.0" },
    { execution:       { id: "exec-1" }, status: "accepted", runtimeVersion: "1.0.0" },
    { executionId:     "exec-1", status: "accepted", runtimeVersion: "1.0.0" },  // camelCase w/o "runtime" prefix
  ] as const;

  it.each(INVALID_ID_VARIANTS)(
    "rejects response shape without runtimeExecutionId: %j",
    async (variant) => {
      submitSpy.mockResolvedValue(variant);

      const engine = new OpenClawExecutionEngine(MOCK_CONFIG as any);
      const err = await engine.submitExecution(makePackage()).catch(e => e);

      expect((err as { code?: string }).code).toBe("MALFORMED_BROKER_RESPONSE");
    },
  );

  const INVALID_STATUS_VALUES = [
    "success", "ok", "running", "started", "complete", "done", "error", "1", "",
  ] as const;

  it.each(INVALID_STATUS_VALUES)(
    "rejects status value not in enum (accepted|queued|rejected): '%s'",
    async (status) => {
      submitSpy.mockResolvedValue({
        runtimeExecutionId: "exec-1",
        status,
        runtimeVersion:     "1.0.0",
      });

      const engine = new OpenClawExecutionEngine(MOCK_CONFIG as any);
      const err = await engine.submitExecution(makePackage()).catch(e => e);

      expect((err as { code?: string }).code).toBe("MALFORMED_BROKER_RESPONSE");
    },
  );
});

// ─── Network errors ───────────────────────────────────────────────────────────

describe("OpenClaw adapter contract — network / transport errors", () => {
  it("broker timeout — throws and marks session failed in DB", async () => {
    submitSpy.mockRejectedValue(
      Object.assign(new Error("OpenClaw broker request timed out"), { name: "BrokerRequestError" }),
    );

    const engine = new OpenClawExecutionEngine(MOCK_CONFIG as any);
    const err = await engine.submitExecution(makePackage()).catch(e => e);

    expect(err).toBeInstanceOf(Error);
    expect((err as Error).message).toMatch(/timed out/);

    // DB must have been updated to mark the session failed.
    // mockDbUpdate is the underlying spy (db.update is a proxy through it).
    expect(mockDbUpdate).toHaveBeenCalled();
  });

  it("broker connection refused — throws and does not return a result", async () => {
    submitSpy.mockRejectedValue(
      Object.assign(new Error("connect ECONNREFUSED 127.0.0.1:19002"), { code: "ECONNREFUSED" }),
    );

    const engine = new OpenClawExecutionEngine(MOCK_CONFIG as any);
    await expect(engine.submitExecution(makePackage())).rejects.toThrow("ECONNREFUSED");
  });
});

// ─── Boundary log ─────────────────────────────────────────────────────────────

describe("OpenClaw adapter contract — safe boundary log", () => {
  it("emits structured log with safe fields only — no prompts, no tenantId, no credentials", async () => {
    submitSpy.mockResolvedValue({
      runtimeExecutionId: "runtime-exec-log-test",
      status:             "accepted",
      runtimeVersion:     "1.0.0",
    });

    const logSpy = vi.spyOn(console, "info").mockImplementation(() => {});

    const engine = new OpenClawExecutionEngine(MOCK_CONFIG as any);
    await engine.submitExecution(makePackage());

    // Find the boundary log entry (produced by the safe boundary log added to submitExecution)
    const boundaryCall = logSpy.mock.calls.find(
      (args) => typeof args[0] === "string" && (args[0] as string).includes("OpenClaw"),
    );

    expect(boundaryCall, "Boundary log must be emitted").toBeDefined();

    const parsed = JSON.parse(boundaryCall![0] as string) as Record<string, unknown>;

    // Required diagnostic fields
    expect(parsed.adapterName).toBe("openclaw-broker");
    expect(parsed.executionId).toBe("exec-contract-1");
    expect(parsed.correlationId).toBe("exec-contract-1");
    expect(parsed.responseKeys).toEqual(
      expect.arrayContaining(["runtimeExecutionId", "status", "runtimeVersion"]),
    );
    expect(parsed.hasRuntimeExecutionId).toBe(true);
    expect(parsed.hasStatus).toBe(true);
    expect(parsed.responseStatus).toBe("accepted");
    expect(parsed.httpStatus).toBe(202);

    // Safety checks — these must NEVER appear in the log
    const logStr = JSON.stringify(parsed);
    expect(logStr).not.toMatch(/instruction/i);
    expect(logStr).not.toMatch(/authToken/i);
    expect(logStr).not.toMatch(/password/i);
    expect(logStr).not.toMatch(/tenantId/i);    // tenant data must not be logged at the boundary
    expect(logStr).not.toMatch(/organizationId/i);

    logSpy.mockRestore();
  });
});
