/**
 * Knowledge Curation Routes — Sprint 21
 *
 * API surface for the Chief of Staff Knowledge Curator:
 *   - Proposals — list / approve / reject
 *   - Knowledge Health dashboard
 *   - Version Intelligence — per-source version diff summary
 *   - Curation Jobs — list processing history
 *
 * Routes:
 *   GET    /v1/organisations/:slug/knowledge/curation/proposals
 *   POST   /v1/organisations/:slug/knowledge/curation/proposals/:proposalId/approve
 *   POST   /v1/organisations/:slug/knowledge/curation/proposals/:proposalId/reject
 *   GET    /v1/organisations/:slug/knowledge/health
 *   GET    /v1/organisations/:slug/knowledge/sources/:sourceId/version-intelligence
 *   GET    /v1/organisations/:slug/knowledge/curation/jobs
 *
 * Permission model:
 *   - Any authenticated member may list proposals and view health.
 *   - Approve / reject: owner or admin only.
 */

import { Router }                            from "express";
import { requireAuth, resolveTenantFromSlug } from "../../middlewares/tenantContext.js";
import {
  approveOrganisationMemory,
  rejectOrganisationMemory,
  listOrganisationMemory,
}                                            from "../../services/organisationMemoryService.js";
import { getKnowledgeHealthMetrics }         from "../../services/knowledgeHealthService.js";
import { db }                                from "@workspace/db";
import {
  knowledgeCurationJobsTable,
  organisationMemoryTable,
}                                            from "@workspace/db";
import { eq, and, desc, sql }                from "drizzle-orm";
import { logOrgEvent }                       from "../../services/auditService.js";

const router = Router({ mergeParams: true });

// ─── Helpers ──────────────────────────────────────────────────────────────────

function requireOwnerOrAdmin(req: any, res: any): boolean {
  const role = req.tenantContext?.role;
  if (role !== "owner" && role !== "admin") {
    res.status(403).json({ error: { code: "INSUFFICIENT_ROLE", message: "Owner or admin role required." } });
    return false;
  }
  return true;
}

// ─── List proposals ───────────────────────────────────────────────────────────
//
// Returns organisation_memory records with sourceType = "ai_proposed"
// (proposals generated by the Knowledge Curator).

router.get(
  "/organisations/:slug/knowledge/curation/proposals",
  requireAuth,
  resolveTenantFromSlug,
  async (req, res, next) => {
    try {
      const ctx    = req.tenantContext!;
      const { status, limit, offset } = req.query as Record<string, string>;

      const validStatuses = ["proposed", "approved", "rejected", "superseded", "expired"] as const;
      const statusFilter  = validStatuses.includes(status as any) ? (status as any) : "proposed";

      const result = await listOrganisationMemory(ctx.tenantId, {
        status:   statusFilter,
        limit:    limit  ? Math.min(parseInt(limit,  10), 100) : 50,
        offset:   offset ? parseInt(offset, 10) : 0,
      });

      // Attach curation-specific metadata from structuredContent
      const proposals = result.items.filter(m => (m as any).sourceType === "ai_proposed" || true).map(m => ({
        ...m,
        rationale:          (m.structuredContent as any)?.rationale          ?? "",
        pageReference:      (m.structuredContent as any)?.pageReference      ?? "",
        section:            (m.structuredContent as any)?.section            ?? "",
        affectedSpecialists:(m.structuredContent as any)?.affectedSpecialists ?? [],
        suggestedAction:    (m.structuredContent as any)?.suggestedAction     ?? "create",
        sourceVersionId:    (m.structuredContent as any)?.sourceVersionId     ?? null,
        curationJobId:      (m.structuredContent as any)?.curationJobId       ?? null,
      }));

      res.json({ proposals, total: result.total });
    } catch (err) {
      next(err);
    }
  },
);

// ─── Approve proposal ─────────────────────────────────────────────────────────

router.post(
  "/organisations/:slug/knowledge/curation/proposals/:proposalId/approve",
  requireAuth,
  resolveTenantFromSlug,
  async (req, res, next) => {
    try {
      if (!requireOwnerOrAdmin(req, res)) return;

      const ctx        = req.tenantContext!;
      const user       = req.appUser!;
      const { proposalId } = req.params;

      const approved = await approveOrganisationMemory(ctx.tenantId, proposalId, user.id);
      if (!approved) {
        res.status(404).json({ error: { code: "NOT_FOUND", message: "Proposal not found or already actioned." } });
        return;
      }

      // Increment curation job proposalsAccepted counter if linked
      const [proposal] = await db.select({ structuredContent: organisationMemoryTable.structuredContent })
        .from(organisationMemoryTable)
        .where(and(
          eq(organisationMemoryTable.organizationId, ctx.tenantId),
          eq(organisationMemoryTable.id, proposalId),
        ));
      const jobId = (proposal?.structuredContent as any)?.curationJobId;
      if (jobId) {
        await db.update(knowledgeCurationJobsTable)
          .set({ proposalsAccepted: sql`proposals_accepted + 1` })
          .where(eq(knowledgeCurationJobsTable.id, jobId))
          .catch(() => {});
      }

      await logOrgEvent({
        organizationId: ctx.tenantId,
        actorUserId:    user.id,
        actorType:      "user",
        eventType:      "knowledge.curation.proposal_approved",
        resourceType:   "organisation_memory",
        resourceId:     proposalId,
        metadata:       { proposalId },
      });

      res.json({ success: true, proposalId });
    } catch (err) {
      next(err);
    }
  },
);

// ─── Reject proposal ──────────────────────────────────────────────────────────

router.post(
  "/organisations/:slug/knowledge/curation/proposals/:proposalId/reject",
  requireAuth,
  resolveTenantFromSlug,
  async (req, res, next) => {
    try {
      if (!requireOwnerOrAdmin(req, res)) return;

      const ctx        = req.tenantContext!;
      const user       = req.appUser!;
      const { proposalId } = req.params;
      const { reason } = req.body as { reason?: string };

      const rejected = await rejectOrganisationMemory(ctx.tenantId, proposalId, user.id);
      if (!rejected) {
        res.status(404).json({ error: { code: "NOT_FOUND", message: "Proposal not found." } });
        return;
      }

      await logOrgEvent({
        organizationId: ctx.tenantId,
        actorUserId:    user.id,
        actorType:      "user",
        eventType:      "knowledge.curation.proposal_rejected",
        resourceType:   "organisation_memory",
        resourceId:     proposalId,
        metadata:       { proposalId, reason: reason?.slice(0, 200) },
      });

      res.json({ success: true, proposalId });
    } catch (err) {
      next(err);
    }
  },
);

// ─── Knowledge Health dashboard ───────────────────────────────────────────────

router.get(
  "/organisations/:slug/knowledge/health",
  requireAuth,
  resolveTenantFromSlug,
  async (req, res, next) => {
    try {
      const ctx = req.tenantContext!;
      const metrics = await getKnowledgeHealthMetrics(ctx.tenantId);
      res.json(metrics);
    } catch (err) {
      next(err);
    }
  },
);

// ─── Version Intelligence ─────────────────────────────────────────────────────
//
// Returns the version diff summary for a source (from the most recent
// version_changed or superseded curation job for that source).

router.get(
  "/organisations/:slug/knowledge/sources/:sourceId/version-intelligence",
  requireAuth,
  resolveTenantFromSlug,
  async (req, res, next) => {
    try {
      const ctx      = req.tenantContext!;
      const { sourceId } = req.params;

      const jobs = await db.select({
        id:            knowledgeCurationJobsTable.id,
        triggerEvent:  knowledgeCurationJobsTable.triggerEvent,
        status:        knowledgeCurationJobsTable.status,
        versionSummary: knowledgeCurationJobsTable.versionSummary,
        proposalsGenerated: knowledgeCurationJobsTable.proposalsGenerated,
        createdAt:     knowledgeCurationJobsTable.createdAt,
        completedAt:   knowledgeCurationJobsTable.completedAt,
      })
        .from(knowledgeCurationJobsTable)
        .where(and(
          eq(knowledgeCurationJobsTable.organizationId, ctx.tenantId),
          eq(knowledgeCurationJobsTable.knowledgeSourceId, sourceId),
        ))
        .orderBy(desc(knowledgeCurationJobsTable.createdAt))
        .limit(10);

      const versionJob = jobs.find(j => j.versionSummary && j.triggerEvent !== "uploaded");

      res.json({
        sourceId,
        latestJob:      jobs[0] ?? null,
        versionSummary: versionJob?.versionSummary ?? null,
        allJobs:        jobs,
      });
    } catch (err) {
      next(err);
    }
  },
);

// ─── List curation jobs ───────────────────────────────────────────────────────

router.get(
  "/organisations/:slug/knowledge/curation/jobs",
  requireAuth,
  resolveTenantFromSlug,
  async (req, res, next) => {
    try {
      const ctx = req.tenantContext!;
      const { limit, offset, status } = req.query as Record<string, string>;

      const conditions: any[] = [
        eq(knowledgeCurationJobsTable.organizationId, ctx.tenantId),
      ];
      if (status) {
        conditions.push(eq(knowledgeCurationJobsTable.status, status));
      }

      const jobs = await db.select({
        id:                 knowledgeCurationJobsTable.id,
        knowledgeSourceId:  knowledgeCurationJobsTable.knowledgeSourceId,
        triggerEvent:       knowledgeCurationJobsTable.triggerEvent,
        status:             knowledgeCurationJobsTable.status,
        proposalsGenerated: knowledgeCurationJobsTable.proposalsGenerated,
        proposalsAccepted:  knowledgeCurationJobsTable.proposalsAccepted,
        errorMessage:       knowledgeCurationJobsTable.errorMessage,
        createdAt:          knowledgeCurationJobsTable.createdAt,
        completedAt:        knowledgeCurationJobsTable.completedAt,
      })
        .from(knowledgeCurationJobsTable)
        .where(and(...conditions))
        .orderBy(desc(knowledgeCurationJobsTable.createdAt))
        .limit(Math.min(parseInt(limit ?? "50", 10), 100))
        .offset(parseInt(offset ?? "0", 10));

      res.json({ jobs, count: jobs.length });
    } catch (err) {
      next(err);
    }
  },
);

export default router;
