/**
 * Worker Profile Registry — Sprint 2 Architecture Correction
 *
 * A Worker Profile defines what a future OpenClaw runtime may access and do
 * when executing on behalf of a Workforce Role (AI Specialist).
 *
 * Worker Profiles are pure metadata — no live permissions, no credentials,
 * no connector secrets. They define intent boundaries for future enforcement.
 *
 * Conceptual chain:
 *   Chief of Staff → Workforce Role → Worker Profile → Future OpenClaw Runtime
 *
 * Rules:
 * - One Workforce Role may reference one or more Worker Profiles.
 * - OpenClaw (future) selects the appropriate profile at execution time.
 * - No browser domains, local paths, or connector credentials are live yet.
 * - Deprecated legacy Marketing profiles remain status: "coming_soon".
 */

import type {
  WorkerProfileStatus,
  ExecutionChannel,
  ToolCategory,
  ConnectorCategory,
  RiskLevel,
} from "@workspace/shared";

// ─── Interface ────────────────────────────────────────────────────────────────

export interface WorkerProfile {
  /** Unique ID, e.g. "wp_chief_of_staff" */
  id: string;
  /** Machine-readable code, e.g. "chief_of_staff_profile" */
  code: string;
  /** Human-readable name */
  displayName: string;
  /** What this profile permits and why */
  description: string;
  /** Execution surfaces this profile may use (intentional, not yet enforced) */
  allowedExecutionChannels: ExecutionChannel[];
  /** Logical tool groupings this profile may invoke */
  allowedToolCategories: ToolCategory[];
  /** External connector families this profile may connect to */
  allowedConnectorCategories: ConnectorCategory[];
  /**
   * Permitted web domains for browser channel (empty = none).
   * Populated in a future sprint when web browsing is live.
   */
  allowedBrowserDomains: string[];
  /**
   * Permitted local file path categories (empty = none).
   * Populated in a future sprint when local file access is live.
   */
  allowedLocalPathCategories: string[];
  /**
   * Permitted host application categories (empty = none).
   * Populated in a future sprint when desktop automation is live.
   */
  allowedApplicationCategories: string[];
  /** Actions this profile may never perform, regardless of other permissions */
  prohibitedActions: string[];
  /** Actions requiring an additional approval before OpenClaw may execute */
  approvalRequiredActions: string[];
  /** Risk classification — governs oversight, logging requirements, and audit trail depth */
  riskLevel: RiskLevel;
  status: WorkerProfileStatus;
  version: string;
}

// ─── Registry ─────────────────────────────────────────────────────────────────

export const WORKER_PROFILES: WorkerProfile[] = [

  // ── Core Workforce ──────────────────────────────────────────────────────────

  {
    id: "wp_chief_of_staff",
    code: "chief_of_staff_profile",
    displayName: "Chief of Staff — Worker Profile",
    description: "Orchestration-only profile. Routes tasks and summarises output. No direct data access, no external connectors.",
    allowedExecutionChannels: ["internal_api"],
    allowedToolCategories: ["search_tools", "reporting_tools"],
    allowedConnectorCategories: [],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["modify_data", "delete_data", "send_external_communication"],
    approvalRequiredActions: [],
    riskLevel: "low",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_executive_assistant",
    code: "executive_assistant_profile",
    displayName: "Executive Assistant — Worker Profile",
    description: "Calendar and communication profile. May read and write calendar events, draft emails. Cannot send emails without approval.",
    allowedExecutionChannels: ["internal_api", "calendar_system", "email_system"],
    allowedToolCategories: ["calendar_tools", "communication_tools"],
    allowedConnectorCategories: ["calendar_system", "email_system"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["delete_calendar_events_for_others", "access_private_correspondence"],
    approvalRequiredActions: ["send_email_on_behalf_of_user", "book_meeting_with_external_parties"],
    riskLevel: "low",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_research_specialist",
    code: "research_specialist_profile",
    displayName: "Research Specialist — Worker Profile",
    description: "Read-only research profile. May search the web (approved domains) and read internal documents. Cannot write or send.",
    allowedExecutionChannels: ["internal_api", "web_browser", "document_store"],
    allowedToolCategories: ["search_tools", "document_tools"],
    allowedConnectorCategories: ["document_management"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["submit_forms", "authenticate_to_external_systems", "download_files"],
    approvalRequiredActions: ["access_paywalled_content"],
    riskLevel: "low",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_document_specialist",
    code: "document_specialist_profile",
    displayName: "Document Specialist — Worker Profile",
    description: "Document creation and review profile. May read and write to the organisation document store.",
    allowedExecutionChannels: ["internal_api", "document_store"],
    allowedToolCategories: ["document_tools"],
    allowedConnectorCategories: ["document_management"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["delete_documents_permanently", "publish_externally"],
    approvalRequiredActions: ["share_document_with_external_party"],
    riskLevel: "low",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_calendar_specialist",
    code: "calendar_specialist_profile",
    displayName: "Calendar Specialist — Worker Profile",
    description: "Calendar management profile. May manage all calendar events within the organisation calendar system.",
    allowedExecutionChannels: ["internal_api", "calendar_system"],
    allowedToolCategories: ["calendar_tools"],
    allowedConnectorCategories: ["calendar_system"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["delete_past_events", "access_private_calendars_without_delegation"],
    approvalRequiredActions: ["book_external_venue", "modify_leadership_calendar"],
    riskLevel: "low",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_communication_specialist",
    code: "communication_specialist_profile",
    displayName: "Communication Specialist — Worker Profile",
    description: "Outbound communication profile. May draft communications and stage them for approval before sending.",
    allowedExecutionChannels: ["internal_api", "email_system"],
    allowedToolCategories: ["communication_tools"],
    allowedConnectorCategories: ["email_system"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["send_unsolicited_bulk_communication", "impersonate_executive"],
    approvalRequiredActions: ["send_email", "publish_announcement"],
    riskLevel: "low",
    status: "active",
    version: "1.0.0",
  },

  // ── Compliance Workforce ────────────────────────────────────────────────────

  {
    id: "wp_compliance_officer",
    code: "compliance_officer_profile",
    displayName: "Compliance Officer — Worker Profile",
    description: "Compliance review profile. May read NDIS portal data, review internal documents, and complete compliance forms.",
    allowedExecutionChannels: ["internal_api", "document_store", "database_query"],
    allowedToolCategories: ["document_tools", "search_tools", "form_tools"],
    allowedConnectorCategories: ["ndis_portal", "document_management"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["submit_ndis_claims", "modify_participant_records", "delete_compliance_records"],
    approvalRequiredActions: ["submit_reportable_event", "generate_external_compliance_report"],
    riskLevel: "medium",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_compliance_quality_manager",
    code: "compliance_quality_manager_profile",
    displayName: "Compliance & Quality Manager — Worker Profile",
    description: "Compliance assurance and quality-management profile. May read approved compliance/quality knowledge, query internal assurance data, and draft reports or corrective-action recommendations. External/regulatory actions require approval; record mutation outside assurance tracking is prohibited.",
    allowedExecutionChannels: ["internal_api", "document_store", "database_query"],
    allowedToolCategories: ["document_tools", "search_tools", "data_tools", "reporting_tools", "form_tools"],
    allowedConnectorCategories: ["document_management"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: [
      "submit_regulatory_notification",
      "modify_participant_records",
      "modify_staff_records",
      "publish_policy_without_approval",
      "close_serious_incident",
      "certify_compliance_without_evidence",
      "delete_compliance_records",
    ],
    approvalRequiredActions: [
      "generate_external_compliance_report",
      "submit_regulator_communication",
      "close_high_risk_corrective_action",
      "update_compliance_register_status",
      "escalate_serious_non_conformance",
    ],
    riskLevel: "high",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_quality_officer",
    code: "quality_officer_profile",
    displayName: "Quality Officer — Worker Profile",
    description: "Quality assessment profile. Read-only access to service records; may create quality review documents.",
    allowedExecutionChannels: ["internal_api", "document_store"],
    allowedToolCategories: ["document_tools", "reporting_tools"],
    allowedConnectorCategories: ["document_management"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["modify_service_records", "delete_quality_reports"],
    approvalRequiredActions: ["issue_quality_alert", "escalate_to_regulator"],
    riskLevel: "low",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_policy_officer",
    code: "policy_officer_profile",
    displayName: "Policy Officer — Worker Profile",
    description: "Policy management profile. May draft and update policies in the document store. Publishing requires approval.",
    allowedExecutionChannels: ["internal_api", "document_store"],
    allowedToolCategories: ["document_tools", "search_tools"],
    allowedConnectorCategories: ["document_management"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["publish_policy_without_approval", "delete_policy_version"],
    approvalRequiredActions: ["publish_policy", "archive_policy"],
    riskLevel: "low",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_policy_governance_specialist",
    code: "policy_governance_specialist_profile",
    displayName: "Policy & Governance Specialist — Worker Profile",
    description: "Policy and governance architecture profile. May read organisational policies, procedures, templates, governance records, approved authority evidence and relevant domain evidence; analyse policy gaps, governance conflicts, regulatory-change impact, delegations, lifecycle status and implementation requirements; and draft policies, frameworks, reviews, governance briefs and decision papers. Publishing, controlled-status changes and external governance communications are approval-gated. Self-approval, invented legal authority, domain decisions, evidence-free compliance certification and record mutation are prohibited.",
    allowedExecutionChannels: ["internal_api", "document_store", "database_query"],
    allowedToolCategories: ["document_tools", "search_tools", "data_tools", "reporting_tools", "form_tools"],
    allowedConnectorCategories: ["document_management"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: [
      "self_approve_policy",
      "publish_policy_without_approval",
      "invent_legal_authority",
      "make_clinical_decision",
      "make_practitioner_decision",
      "override_domain_authority",
      "mutate_participant_record",
      "mutate_staff_record",
      "evidence_free_compliance_certification",
      "unrestricted_regulator_submission",
      "alter_technical_access_permissions",
      "delete_policy_version",
    ],
    approvalRequiredActions: [
      "publish_policy",
      "archive_policy",
      "supersede_policy",
      "change_controlled_governance_status",
      "change_policy_register_status",
      "send_external_governance_communication",
      "recommend_high_impact_governance_change",
    ],
    riskLevel: "high",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_incident_review_officer",
    code: "incident_review_officer_profile",
    displayName: "Incident Review Officer — Worker Profile",
    description: "Incident investigation profile. May query incident records, access related participant data (read-only), and draft reports.",
    allowedExecutionChannels: ["internal_api", "document_store", "database_query"],
    allowedToolCategories: ["document_tools", "form_tools", "data_tools"],
    allowedConnectorCategories: ["ndis_portal", "document_management"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["modify_incident_records_after_submission", "identify_reporter_anonymously"],
    approvalRequiredActions: ["submit_reportable_incident_to_ndis", "notify_police", "notify_regulator"],
    riskLevel: "high",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_incident_safeguarding_specialist",
    code: "incident_safeguarding_specialist_profile",
    displayName: "Incident & Safeguarding Specialist — Worker Profile",
    description: "Incident and safeguarding review profile. May read incident/safeguarding records, query authorised evidence, and draft incident reviews, safeguarding assessments, escalation briefs and closure-readiness recommendations. External notifications, final closure and record mutation are gated or prohibited.",
    allowedExecutionChannels: ["internal_api", "document_store", "database_query"],
    allowedToolCategories: ["document_tools", "search_tools", "data_tools", "reporting_tools", "form_tools"],
    allowedConnectorCategories: ["document_management"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: [
      "submit_regulatory_notification",
      "submit_reportable_incident_to_ndis",
      "notify_police",
      "close_serious_incident",
      "modify_incident_records_after_submission",
      "modify_participant_records",
      "modify_staff_records",
      "authorise_restrictive_practice",
      "modify_behavioural_support_plan_without_approval",
      "make_clinical_decision",
    ],
    approvalRequiredActions: [
      "generate_external_incident_report",
      "send_safeguarding_escalation",
      "update_incident_review_status",
      "update_safeguarding_action_status",
      "generate_rp_summary_report",
      "document_rp_use",
      "recommend_serious_incident_closure",
    ],
    riskLevel: "high",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_corrective_action_officer",
    code: "corrective_action_officer_profile",
    displayName: "Corrective Action Officer — Worker Profile",
    description: "Corrective action management profile. May create and update action plans linked to audits and incidents.",
    allowedExecutionChannels: ["internal_api", "document_store"],
    allowedToolCategories: ["document_tools", "form_tools"],
    allowedConnectorCategories: ["document_management"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["close_action_without_evidence", "delete_corrective_action_record"],
    approvalRequiredActions: ["close_corrective_action", "escalate_overdue_action"],
    riskLevel: "medium",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_restrictive_practice_officer",
    code: "restrictive_practice_officer_profile",
    displayName: "Restrictive Practice Officer — Worker Profile",
    description: "Restrictive practice oversight profile. Highest-sensitivity compliance profile; all external submissions require explicit approval.",
    allowedExecutionChannels: ["internal_api", "document_store", "database_query"],
    allowedToolCategories: ["document_tools", "form_tools", "data_tools"],
    allowedConnectorCategories: ["ndis_portal", "document_management"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["authorise_restrictive_practice", "modify_behavioural_support_plan_without_approval"],
    approvalRequiredActions: ["submit_rp_report_to_ndis", "document_rp_use", "generate_rp_summary_report"],
    riskLevel: "high",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_authorised_program_officer",
    code: "authorised_program_officer_profile",
    displayName: "Authorised Program Officer — Worker Profile",
    description: "Restrictive-practice governance profile. May read approved BSP/RP, authority, consent, register, incident and policy evidence; analyse RP authority status, usage patterns, monthly reporting and reduction/elimination governance; and draft internal governance reports. External submissions, authorisation decisions, BSP changes, clinical/practitioner/legal decisions and participant/staff mutation are prohibited or approval-gated.",
    allowedExecutionChannels: ["internal_api", "document_store", "database_query"],
    allowedToolCategories: ["document_tools", "search_tools", "data_tools", "reporting_tools", "form_tools"],
    allowedConnectorCategories: ["document_management"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: [
      "authorise_restrictive_practice",
      "approve_restrictive_practice_authorisation",
      "modify_behavioural_support_plan_without_approval",
      "author_behaviour_support_plan",
      "make_behaviour_support_practitioner_decision",
      "make_clinical_decision",
      "prescribe_medication",
      "make_legal_determination",
      "modify_participant_records",
      "modify_staff_records",
      "notify_police",
      "submit_regulatory_notification_without_approval",
      "certify_rp_compliance_without_evidence",
    ],
    approvalRequiredActions: [
      "submit_rp_report_to_ndis",
      "submit_monthly_rp_report",
      "generate_external_rp_report",
      "submit_regulator_communication",
      "update_rp_register_status",
      "update_rp_governance_tracking",
      "document_rp_use",
      "send_rp_governance_escalation",
      "close_high_risk_rp_governance_action",
    ],
    riskLevel: "high",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_behaviour_support_implementation_specialist",
    code: "behaviour_support_implementation_specialist_profile",
    displayName: "Behaviour Support Implementation Specialist — Worker Profile",
    description: "Behaviour-support implementation profile. May read approved BSP, participant/client support records, behaviour observations, implementation evidence, incident/RP evidence where relevant, and approved policies; analyse implementation fidelity, behaviour/context patterns, variance and evidence gaps; and draft internal implementation guides, fidelity reviews, behaviour data analyses and practitioner-review briefs. BSP amendment, practitioner strategy, RP authorisation, clinical/legal/disciplinary decisions and record mutation are prohibited or approval-gated.",
    allowedExecutionChannels: ["internal_api", "document_store", "database_query"],
    allowedToolCategories: ["document_tools", "search_tools", "data_tools", "reporting_tools", "form_tools"],
    allowedConnectorCategories: ["document_management"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: [
      "author_behaviour_support_plan",
      "amend_behaviour_support_plan",
      "approve_behaviour_support_plan",
      "make_behaviour_support_practitioner_decision",
      "create_practitioner_level_strategy",
      "authorise_restrictive_practice",
      "submit_monthly_rp_report",
      "make_clinical_decision",
      "prescribe_medication",
      "make_legal_determination",
      "modify_participant_records",
      "modify_staff_records",
      "make_staff_disciplinary_decision",
      "notify_police",
      "submit_regulatory_notification_without_approval",
      "certify_implementation_without_evidence",
    ],
    approvalRequiredActions: [
      "publish_bsp_implementation_guidance",
      "update_implementation_action_status",
      "create_external_practitioner_review_brief",
      "recommend_significant_service_practice_change",
      "share_behaviour_data_analysis_externally",
      "update_fidelity_review_status",
    ],
    riskLevel: "high",
    status: "active",
    version: "1.0.0",
  },

  // ── Operations Workforce ────────────────────────────────────────────────────

  {
    id: "wp_operations_manager",
    code: "operations_manager_profile",
    displayName: "Operations Manager — Worker Profile",
    description: "Operations oversight profile. May query operational data and generate capacity and workflow reports.",
    allowedExecutionChannels: ["internal_api", "database_query"],
    allowedToolCategories: ["data_tools", "reporting_tools"],
    allowedConnectorCategories: [],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["modify_staff_records", "adjust_service_agreements_unilaterally"],
    approvalRequiredActions: ["generate_executive_operations_report", "trigger_capacity_review"],
    riskLevel: "medium",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_service_delivery_coordinator",
    code: "service_delivery_coordinator_profile",
    displayName: "Service Delivery Coordinator — Worker Profile",
    description: "Service-delivery implementation profile. May read approved support plans, service agreements, schedules, case notes and delivery records; analyse delivery gaps, implementation fidelity and goal-related evidence; and draft service delivery plans, implementation reviews, coordination briefs and gap reports.",
    allowedExecutionChannels: ["internal_api", "document_store", "database_query"],
    allowedToolCategories: ["document_tools", "data_tools", "reporting_tools"],
    allowedConnectorCategories: ["document_management"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: [
      "modify_participant_service_records",
      "cancel_service_delivery",
      "make_clinical_decision",
      "author_behaviour_support_plan",
      "amend_behaviour_support_plan",
      "approve_behaviour_support_plan",
      "authorise_restrictive_practice",
      "make_disciplinary_finding",
      "change_service_agreement_unilaterally",
      "construct_roster",
      "assign_staff_to_shift",
      "make_legal_determination",
      "certify_participant_outcome_without_evidence",
    ],
    approvalRequiredActions: [
      "generate_participant_outcome_report",
      "publish_service_delivery_report",
      "recommend_material_service_plan_change",
      "send_external_service_communication",
      "update_service_delivery_action_status",
      "share_participant_service_evidence_externally",
    ],
    riskLevel: "medium",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_roster_coordinator",
    code: "roster_coordinator_profile",
    displayName: "Roster Coordinator — Worker Profile",
    description: "Roster management profile. May query and analyse rosters; write access to roster data requires approval.",
    allowedExecutionChannels: ["internal_api", "database_query", "calendar_system"],
    allowedToolCategories: ["calendar_tools", "data_tools"],
    allowedConnectorCategories: ["calendar_system"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["publish_roster_without_review", "modify_award_interpretation"],
    approvalRequiredActions: ["publish_roster", "override_shift_allocation"],
    riskLevel: "low",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_workforce_rostering_coordinator",
    code: "workforce_rostering_coordinator_profile",
    displayName: "Workforce Rostering Coordinator — Worker Profile",
    description: "Current-v2 rostering profile. May read current roster, service requirements, support ratios, worker availability, approved leave, verified eligibility/status and scheduling rules; analyse coverage, vacancies, conflicts, utilisation and roster options; and draft rosters, coverage plans, shift allocation proposals, vacancy reports and exception reports.",
    allowedExecutionChannels: ["internal_api", "database_query", "calendar_system", "document_store"],
    allowedToolCategories: ["calendar_tools", "data_tools", "reporting_tools", "document_tools"],
    allowedConnectorCategories: ["calendar_system", "hr_system", "document_management"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: [
      "change_required_support_ratio",
      "invent_worker_availability",
      "override_verified_credential_restriction",
      "certify_worker_qualification",
      "certify_worker_credential",
      "change_employment_conditions",
      "calculate_final_pay_entitlement",
      "alter_payroll",
      "make_final_schads_determination",
      "make_legal_determination",
      "make_disciplinary_decision",
      "modify_participant_service_records",
      "modify_staff_records",
      "make_clinical_decision",
      "modify_behaviour_support_plan",
      "authorise_restrictive_practice",
      "bypass_hard_safety_constraint",
      "remove_blueprint_prohibition",
      "expand_own_authority",
    ],
    approvalRequiredActions: [
      "publish_roster",
      "finalise_roster",
      "materially_modify_active_roster",
      "replace_assigned_worker_after_publication",
      "send_external_roster_communication",
      "override_soft_scheduling_constraint",
      "approve_high_impact_scheduling_change",
    ],
    riskLevel: "medium",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_asset_coordinator",
    code: "asset_coordinator_profile",
    displayName: "Asset Coordinator — Worker Profile",
    description: "Asset management profile. May query, update, and report on organisational assets.",
    allowedExecutionChannels: ["internal_api", "database_query"],
    allowedToolCategories: ["data_tools", "form_tools"],
    allowedConnectorCategories: [],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["write_off_asset_without_approval", "dispose_of_asset"],
    approvalRequiredActions: ["record_asset_disposal", "initiate_procurement"],
    riskLevel: "low",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_workflow_coordinator",
    code: "workflow_coordinator_profile",
    displayName: "Workflow Coordinator — Worker Profile",
    description: "Business process design profile. May create and document operational workflows in the document store.",
    allowedExecutionChannels: ["internal_api", "document_store"],
    allowedToolCategories: ["document_tools", "data_tools"],
    allowedConnectorCategories: ["document_management"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["activate_automated_workflow_without_approval"],
    approvalRequiredActions: ["activate_new_operational_workflow", "deprecate_existing_workflow"],
    riskLevel: "low",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_process_asset_coordinator",
    code: "process_asset_coordinator_profile",
    displayName: "Process & Asset Coordinator — Worker Profile",
    description: "Current-v2 process and asset coordination profile. May read approved policies/procedures, workflow/system records, operational records, asset registers, maintenance/inspection evidence and related templates within task scope; analyse process mechanics, controls, handoffs, SOPs, work instructions, operational registers, asset lifecycle, condition, defects and due-status evidence; and draft process maps, SOPs, checklists, control matrices, asset reports and improvement recommendations. Policy approval, compliance certification, service-delivery decisions, roster/payroll/HR decisions, safety or technical certification, material purchasing/disposal and evidence fabrication are prohibited.",
    allowedExecutionChannels: ["internal_api", "document_store", "database_query"],
    allowedToolCategories: ["document_tools", "search_tools", "data_tools", "reporting_tools", "form_tools"],
    allowedConnectorCategories: ["document_management", "hr_system"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: [
      "approve_policy",
      "reinterpret_regulation_as_policy",
      "change_governance_requirement",
      "certify_compliance",
      "self_audit_certify_process",
      "make_service_delivery_decision",
      "publish_roster",
      "make_payroll_decision",
      "make_hr_disciplinary_decision",
      "certify_safety_critical_asset",
      "technical_certification_without_authority",
      "approve_material_purchase",
      "dispose_material_asset",
      "fabricate_process_evidence",
      "fabricate_asset_evidence",
      "bypass_automation_approval",
    ],
    approvalRequiredActions: [
      "publish_controlled_operational_procedure",
      "replace_controlled_sop",
      "material_workflow_change",
      "mutate_asset_register",
      "change_safety_critical_asset_status",
      "initiate_asset_procurement_request",
      "record_asset_disposal",
      "send_external_vendor_instruction",
      "activate_workflow_automation",
    ],
    riskLevel: "high",
    status: "active",
    version: "1.0.0",
  },

  // ── Finance Workforce ───────────────────────────────────────────────────────

  {
    id: "wp_accounts_officer",
    code: "accounts_officer_profile",
    displayName: "Accounts Officer — Worker Profile",
    description: "Accounts management profile. May query and report on accounts payable/receivable. Financial writes require approval.",
    allowedExecutionChannels: ["internal_api", "database_query"],
    allowedToolCategories: ["data_tools", "reporting_tools", "form_tools"],
    allowedConnectorCategories: ["finance_system"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["initiate_payment", "modify_bank_account_details", "override_reconciliation"],
    approvalRequiredActions: ["submit_reconciliation_report", "flag_discrepancy_for_payment"],
    riskLevel: "high",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_payroll_officer",
    code: "payroll_officer_profile",
    displayName: "Payroll Officer — Worker Profile",
    description: "Payroll review profile. Highest-sensitivity finance profile. All payment actions are explicitly prohibited; review and reporting only.",
    allowedExecutionChannels: ["internal_api", "database_query"],
    allowedToolCategories: ["data_tools", "form_tools"],
    allowedConnectorCategories: ["payroll_system", "finance_system"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: [
      "process_payment",
      "modify_bank_account_details",
      "approve_payrun",
      "access_tax_file_numbers",
      "modify_salary_without_approval",
    ],
    approvalRequiredActions: ["submit_payrun_for_approval", "generate_payslips", "reconcile_super"],
    riskLevel: "high",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_payroll_workforce_cost_officer",
    code: "payroll_workforce_cost_officer_profile",
    displayName: "Payroll & Workforce Cost Officer — Worker Profile",
    description: "Current-v2 payroll and workforce-cost profile. May read payroll, timesheet, roster, classification, employment-type, rate, award/instrument, allowance, approved-claim and workforce-cost evidence; analyse payroll treatment, effective dates, discrepancies and cost components; and draft payroll reconciliation, exception, award/rate and workforce-cost reports. Payroll mutation, fund transfer, worked-hour fabrication, classification alteration, roster publication, credential certification, HR discipline, legal/tax-agent advice, clinical/BSP/RP actions and evidence-free pay certification are prohibited.",
    allowedExecutionChannels: ["internal_api", "database_query", "document_store"],
    allowedToolCategories: ["data_tools", "search_tools", "reporting_tools", "document_tools", "form_tools"],
    allowedConnectorCategories: ["payroll_system", "finance_system", "hr_system", "document_management"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: [
      "fabricate_payroll_record",
      "fabricate_timesheet_record",
      "fabricate_rate_or_award_evidence",
      "change_worked_hours_without_verified_authority",
      "alter_worker_classification_without_authority",
      "bypass_industrial_obligation",
      "approve_payrun",
      "process_payment",
      "transfer_funds",
      "modify_bank_account_details",
      "modify_pay_rate_without_authority",
      "publish_roster",
      "assign_worker_to_shift",
      "certify_worker_credentials",
      "make_hr_disciplinary_decision",
      "make_legal_determination",
      "provide_tax_agent_advice",
      "make_clinical_decision",
      "author_behaviour_support_plan",
      "authorise_restrictive_practice",
      "certify_payroll_without_evidence",
      "delete_payroll_or_timesheet_records",
    ],
    approvalRequiredActions: [
      "update_payroll_record",
      "update_payroll_configuration",
      "submit_payroll_correction_recommendation",
      "generate_external_payroll_report",
      "generate_payslips",
      "reconcile_super",
      "submit_payrun_for_approval",
      "share_payroll_analysis_externally",
      "request_fair_work_api_evidence",
      "request_payroll_system_evidence",
      "escalate_underpayment_risk_to_management",
    ],
    riskLevel: "high",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_invoice_specialist",
    code: "invoice_specialist_profile",
    displayName: "Invoice Specialist — Worker Profile",
    description: "Invoice review profile. May query NDIS claim data, validate invoices, and draft invoice reports.",
    allowedExecutionChannels: ["internal_api", "database_query", "document_store"],
    allowedToolCategories: ["data_tools", "document_tools", "form_tools"],
    allowedConnectorCategories: ["finance_system", "ndis_portal"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["submit_ndis_claim_without_approval", "modify_approved_invoice"],
    approvalRequiredActions: ["submit_claim_to_ndis_portal", "reject_invoice"],
    riskLevel: "medium",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_finance_officer",
    code: "finance_officer_profile",
    displayName: "Finance Officer — Worker Profile",
    description: "Current-v2 operational finance profile. May read financial records, invoices, receipts, payment evidence, bank transactions, approval records and supplier/customer statements; analyse reconciliation, transaction matching, coding support, duplicate risk, AP/AR, expense and reimbursement exceptions; and draft operational finance reports. Payment approval, bank transfer, record fabrication/deletion, false reconciliation, unsupported journals, payroll determinations, FP&R budget/forecast authority, tax/legal/audit advice and financial evidence manipulation are prohibited.",
    allowedExecutionChannels: ["internal_api", "database_query", "document_store"],
    allowedToolCategories: ["data_tools", "search_tools", "reporting_tools", "document_tools", "form_tools"],
    allowedConnectorCategories: ["finance_system", "document_management", "ndis_portal"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: [
      "approve_payment_without_authority",
      "execute_bank_transfer",
      "release_supplier_payment",
      "fabricate_receipt",
      "fabricate_invoice",
      "fabricate_financial_record",
      "delete_financial_record",
      "conceal_financial_record",
      "false_reconciliation",
      "create_unsupported_journal",
      "post_unsupported_journal",
      "force_balance_reconciliation",
      "manipulate_financial_evidence",
      "make_payroll_professional_determination",
      "calculate_schads_entitlement",
      "own_budget_forecast_decision",
      "provide_tax_agent_advice",
      "provide_legal_advice",
      "certify_audit_opinion",
      "declare_fraud_without_evidence",
      "change_bank_account_details",
      "approve_material_purchase",
    ],
    approvalRequiredActions: [
      "create_financial_transaction",
      "post_financial_transaction",
      "issue_invoice",
      "apply_credit_note",
      "initiate_refund",
      "change_transaction_coding",
      "change_supplier_financial_record",
      "change_customer_financial_record",
      "initiate_payment",
      "post_material_journal",
      "mutate_financial_record",
      "send_external_finance_communication",
      "submit_bas_inputs_for_review",
      "escalate_payment_discrepancy",
    ],
    riskLevel: "high",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_budget_analyst",
    code: "budget_analyst_profile",
    displayName: "Budget Analyst — Worker Profile",
    description: "Budget analysis profile. Read-only financial data access for variance analysis and budget summaries.",
    allowedExecutionChannels: ["internal_api", "database_query"],
    allowedToolCategories: ["data_tools", "reporting_tools"],
    allowedConnectorCategories: ["finance_system"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["modify_budget_allocations", "approve_budget_variance"],
    approvalRequiredActions: ["publish_budget_report", "share_budget_data_externally"],
    riskLevel: "medium",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_financial_reporting_officer",
    code: "financial_reporting_officer_profile",
    displayName: "Financial Reporting Officer — Worker Profile",
    description: "Financial reporting profile. May prepare financial statements and board-level reports. Distribution requires approval.",
    allowedExecutionChannels: ["internal_api", "database_query", "document_store"],
    allowedToolCategories: ["data_tools", "reporting_tools", "document_tools"],
    allowedConnectorCategories: ["finance_system"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["publish_financials_externally_without_approval", "modify_audited_records"],
    approvalRequiredActions: ["distribute_financial_report", "share_with_board", "submit_to_regulator"],
    riskLevel: "high",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_financial_planning_reporting_manager",
    code: "financial_planning_reporting_manager_profile",
    displayName: "Financial Planning & Reporting Manager — Worker Profile",
    description: "Current-v2 financial planning and reporting profile. May read verified financial actuals, budgets, forecasts, payroll/workforce-cost inputs, operational drivers, commitments and assumptions; analyse variance, forecast, cashflow, scenarios, sensitivity, profitability, KPIs and management reporting; and draft budget, forecast, management-reporting and business-case outputs. Bank transactions, payment execution, journal manipulation, altered actuals, payroll determinations, budget approval, investment execution, false reporting, hidden adverse variance and evidence-free forecast certification are prohibited.",
    allowedExecutionChannels: ["internal_api", "database_query", "document_store"],
    allowedToolCategories: ["data_tools", "search_tools", "reporting_tools", "document_tools", "form_tools"],
    allowedConnectorCategories: ["finance_system", "payroll_system", "document_management"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: [
      "execute_bank_transaction",
      "execute_bank_payment",
      "execute_investment",
      "approve_payment_without_authority",
      "manipulate_journal",
      "alter_reconciled_actuals",
      "rewrite_financial_actuals",
      "make_payroll_professional_determination",
      "calculate_schads_entitlement",
      "approve_budget_beyond_authority",
      "publish_false_financial_report",
      "hide_adverse_variance",
      "fabricate_forecast_assumption",
      "certify_evidence_free_forecast",
      "provide_tax_agent_advice",
      "provide_legal_advice",
      "certify_audit_opinion",
    ],
    approvalRequiredActions: [
      "publish_formal_budget",
      "publish_formal_forecast",
      "materially_revise_approved_budget",
      "materially_revise_approved_forecast",
      "publish_board_pack",
      "publish_external_financial_report",
      "record_authoritative_forecast_version",
      "record_authoritative_budget_version",
      "share_financial_model_externally",
      "issue_material_financial_recommendation",
    ],
    riskLevel: "high",
    status: "active",
    version: "1.0.0",
  },

  // ── HR Workforce ────────────────────────────────────────────────────────────

  {
    id: "wp_hr_officer",
    code: "hr_officer_profile",
    displayName: "HR Officer — Worker Profile",
    description: "HR administration profile. May access HR documents and draft employment-related communications.",
    allowedExecutionChannels: ["internal_api", "document_store"],
    allowedToolCategories: ["document_tools", "communication_tools"],
    allowedConnectorCategories: ["hr_system", "document_management"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["modify_employment_contracts_without_approval", "access_sensitive_medical_records"],
    approvalRequiredActions: ["issue_formal_hr_notice", "initiate_termination_process"],
    riskLevel: "medium",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_recruitment_officer",
    code: "recruitment_officer_profile",
    displayName: "Recruitment Officer — Worker Profile",
    description: "Recruitment profile. May draft job adverts, screen applications (read-only), and send invitation communications.",
    allowedExecutionChannels: ["internal_api", "document_store", "email_system"],
    allowedToolCategories: ["document_tools", "communication_tools", "search_tools"],
    allowedConnectorCategories: ["hr_system", "email_system"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["make_employment_offer_without_approval", "access_referee_contact_details_without_consent"],
    approvalRequiredActions: ["send_job_offer", "reject_candidate_formally"],
    riskLevel: "low",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_learning_coordinator",
    code: "learning_coordinator_profile",
    displayName: "Learning Coordinator — Worker Profile",
    description: "Learning and development profile. May enrol staff in training, track completions, and schedule learning events.",
    allowedExecutionChannels: ["internal_api", "document_store", "calendar_system"],
    allowedToolCategories: ["document_tools", "calendar_tools", "data_tools"],
    allowedConnectorCategories: ["hr_system", "calendar_system"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["mark_mandatory_training_complete_without_evidence"],
    approvalRequiredActions: ["enrol_mandatory_compliance_training", "waive_training_requirement"],
    riskLevel: "low",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_performance_officer",
    code: "performance_officer_profile",
    displayName: "Performance Officer — Worker Profile",
    description: "Performance review profile. May access performance data and draft review documentation; escalation requires approval.",
    allowedExecutionChannels: ["internal_api", "document_store"],
    allowedToolCategories: ["document_tools", "data_tools"],
    allowedConnectorCategories: ["hr_system"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["issue_performance_improvement_plan_without_approval", "access_psychological_assessments"],
    approvalRequiredActions: ["initiate_pip", "escalate_performance_concern_to_leadership"],
    riskLevel: "medium",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_people_culture_manager",
    code: "people_culture_manager_profile",
    displayName: "People & Culture Manager — Worker Profile",
    description: "Current-v2 people-management profile. May read relevant employee records, employment documents, performance/supervision evidence, grievance/complaint evidence and workplace adjustment material within task scope; analyse employment lifecycle, employee relations, procedural fairness, performance, probation, conduct, grievances, people risk and recruitment support; and draft internal HR reports, management recommendations and approval-ready correspondence. Autonomous termination, suspension, severe discipline, evidence-free findings, credential certification, roster publication, payroll determination, legal/clinical/BSP/RP decisions and broad employee-record harvesting are prohibited.",
    allowedExecutionChannels: ["internal_api", "document_store", "database_query", "email_system"],
    allowedToolCategories: ["document_tools", "communication_tools", "search_tools", "data_tools", "reporting_tools", "form_tools"],
    allowedConnectorCategories: ["document_management", "hr_system", "email_system"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: [
      "terminate_employee",
      "suspend_employee_without_approval",
      "make_severe_disciplinary_decision",
      "fabricate_employee_record",
      "fabricate_misconduct_finding",
      "evidence_free_misconduct_finding",
      "discard_required_employee_response",
      "treat_allegation_as_fact",
      "certify_worker_credential",
      "override_worker_eligibility",
      "publish_roster",
      "make_payroll_determination",
      "provide_legal_advice",
      "make_clinical_decision",
      "author_behaviour_support_plan",
      "authorise_restrictive_practice",
      "bulk_export_employee_records",
      "access_unrelated_sensitive_employee_records",
    ],
    approvalRequiredActions: [
      "issue_formal_disciplinary_correspondence",
      "issue_show_cause_correspondence",
      "publish_performance_outcome",
      "publish_performance_improvement_plan",
      "change_employment_status",
      "send_external_employment_communication",
      "mutate_consequential_hr_record",
      "close_employee_relations_case",
      "share_sensitive_employee_information",
    ],
    riskLevel: "high",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_talent_learning_specialist",
    code: "talent_learning_specialist_profile",
    displayName: "Talent & Learning Specialist — Worker Profile",
    description: "Current-v2 learning and capability-development profile. May read relevant learning, training, competency, role, policy, performance, audit and incident-theme evidence within task scope; analyse learning needs, competency gaps, induction, onboarding learning, refresher training, development pathways and learning effectiveness; and draft learning plans, training briefs, capability reports and remediation recommendations. Competency certification, deployment eligibility, compliance override, disciplinary decisions, payroll, roster publication, clinical/BSP/RP/legal decisions and evidence-free certification are prohibited.",
    allowedExecutionChannels: ["internal_api", "document_store", "database_query", "calendar_system"],
    allowedToolCategories: ["document_tools", "search_tools", "data_tools", "reporting_tools", "calendar_tools", "form_tools"],
    allowedConnectorCategories: ["document_management", "hr_system", "calendar_system"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: [
      "certify_competency_without_authority",
      "evidence_free_competency_certification",
      "declare_deployment_eligibility",
      "override_expired_training",
      "override_expired_credential",
      "mark_mandatory_training_complete_without_evidence",
      "treat_attendance_as_competence",
      "treat_future_training_as_current_completion",
      "change_policy_meaning",
      "change_mandatory_learning_requirement",
      "make_disciplinary_decision",
      "terminate_employee",
      "make_payroll_determination",
      "publish_roster",
      "make_clinical_decision",
      "author_behaviour_support_plan",
      "authorise_restrictive_practice",
      "provide_legal_advice",
      "bulk_export_employee_records",
      "access_unrelated_sensitive_employee_records",
    ],
    approvalRequiredActions: [
      "publish_organisation_wide_learning_program",
      "publish_induction_program",
      "publish_mandatory_learning_schedule",
      "communicate_with_external_training_provider",
      "update_authoritative_training_status",
      "share_sensitive_learning_or_performance_information",
      "schedule_mandatory_training_enrolments",
      "create_external_learning_report",
    ],
    riskLevel: "high",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_staff_compliance_officer",
    code: "staff_compliance_officer_profile",
    displayName: "Staff Compliance Officer — Worker Profile",
    description: "Staff compliance profile. May verify NDIS Worker Screening, credentials, and certifications. All external submissions require approval.",
    allowedExecutionChannels: ["internal_api", "database_query", "document_store"],
    allowedToolCategories: ["data_tools", "form_tools", "document_tools"],
    allowedConnectorCategories: ["hr_system", "ndis_portal"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: ["access_worker_screening_raw_results", "suspend_worker_access_unilaterally"],
    approvalRequiredActions: ["flag_worker_screening_risk", "initiate_worker_suspension"],
    riskLevel: "medium",
    status: "active",
    version: "1.0.0",
  },
  {
    id: "wp_workforce_compliance_specialist",
    code: "workforce_compliance_specialist_profile",
    displayName: "Workforce Compliance Specialist — Worker Profile",
    description: "Current-v2 workforce compliance profile. May read workforce compliance requirements, worker credential/screening/check, training, competency and eligibility evidence; analyse currentness, expiry, missing evidence, verification status, deployment eligibility and compliance exceptions; and draft worker compliance assessments, expiry reports, missing-evidence reports and remediation recommendations. Credential fabrication, expiry override, roster publication, HR disciplinary action, payroll/SCHADS decisions, clinical/BSP/RP/legal decisions and mandatory-requirement bypass are prohibited.",
    allowedExecutionChannels: ["internal_api", "document_store", "database_query"],
    allowedToolCategories: ["document_tools", "search_tools", "data_tools", "reporting_tools", "form_tools"],
    allowedConnectorCategories: ["document_management", "hr_system", "ndis_portal"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: [
      "fabricate_worker_credential",
      "fabricate_training_completion",
      "fabricate_screening_clearance",
      "override_credential_expiry",
      "treat_expired_evidence_as_current",
      "mark_unverified_evidence_as_verified",
      "bypass_mandatory_workforce_requirement",
      "publish_roster",
      "assign_worker_to_shift",
      "make_payroll_or_schads_decision",
      "make_hr_disciplinary_decision",
      "make_clinical_decision",
      "author_behaviour_support_plan",
      "authorise_restrictive_practice",
      "make_legal_determination",
      "mutate_participant_record",
      "delete_compliance_records",
    ],
    approvalRequiredActions: [
      "update_worker_compliance_status",
      "verify_credential_against_external_source",
      "record_deployment_restriction",
      "record_compliance_exception",
      "generate_external_workforce_compliance_report",
      "notify_management_of_worker_ineligibility",
      "recommend_employment_follow_up",
    ],
    riskLevel: "high",
    status: "active",
    version: "1.0.0",
  },

  // ── Marketing Workforce ────────────────────────────────────────────────────

  {
    id: "wp_marketing_communications_manager",
    code: "marketing_communications_manager_profile",
    displayName: "Marketing & Communications Manager - Worker Profile",
    description: "Current-v2 marketing and communications profile. May read approved organisation/service facts, professional-owner inputs, brand materials, campaign data, audience research and analytics; draft content, campaigns, communications, public copy, social plans and performance reviews; and prepare external publication packages for approval. Public publication, mass sends, paid launch, crisis statements, material public claims and testimonials require approval. False claims, participant-identifying content without consent, incident disclosures, deceptive marketing and professional-claim fabrication are prohibited.",
    allowedExecutionChannels: ["internal_api", "document_store", "web_browser", "email_system"],
    allowedToolCategories: ["communication_tools", "document_tools", "search_tools", "reporting_tools", "calendar_tools"],
    allowedConnectorCategories: ["document_management", "email_system"],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: [
      "publish_unverified_professional_claim",
      "publish_participant_identifying_content_without_consent",
      "publish_false_testimonial",
      "invent_marketing_statistic",
      "invent_accreditation_or_award",
      "invent_participant_outcome",
      "invent_customer_number_or_partnership",
      "invent_regulatory_approval",
      "invent_pricing_or_fake_scarcity",
      "make_legal_or_regulatory_statement",
      "disclose_incident_or_safeguarding_information",
      "make_clinical_claim_without_evidence",
      "make_bsp_or_rp_claim_without_specialist_evidence",
      "make_financial_claim_without_verified_evidence",
      "publish_discriminatory_targeting",
      "publish_deceptive_marketing",
      "alter_policy_meaning",
      "bypass_publication_approval",
    ],
    approvalRequiredActions: [
      "post_to_social_media",
      "publish_website_content",
      "send_mass_email_or_newsletter",
      "launch_paid_campaign",
      "send_external_stakeholder_communication",
      "publish_media_release",
      "publish_crisis_statement",
      "publish_material_public_claim",
      "publish_testimonial_or_case_study",
      "publish_participant_story",
      "publish_service_promotion",
    ],
    riskLevel: "high",
    status: "active",
    version: "1.0.0",
  },

  // ── Deprecated Marketing Workforce (coming_soon compatibility) ─────────────

  {
    id: "wp_marketing_director",
    code: "marketing_director_profile",
    displayName: "Marketing Director — Worker Profile",
    description: "Marketing strategy profile. Not yet active; permissions will be defined when the Marketing Workforce is released.",
    allowedExecutionChannels: ["internal_api", "document_store", "web_browser"],
    allowedToolCategories: ["document_tools", "communication_tools", "search_tools"],
    allowedConnectorCategories: [],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: [],
    approvalRequiredActions: ["publish_external_campaign"],
    riskLevel: "low",
    status: "coming_soon",
    version: "1.0.0",
  },
  {
    id: "wp_content_strategist",
    code: "content_strategist_profile",
    displayName: "Content Strategist — Worker Profile",
    description: "Content planning profile. Not yet active.",
    allowedExecutionChannels: ["internal_api", "document_store"],
    allowedToolCategories: ["document_tools", "search_tools"],
    allowedConnectorCategories: [],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: [],
    approvalRequiredActions: ["publish_content"],
    riskLevel: "low",
    status: "coming_soon",
    version: "1.0.0",
  },
  {
    id: "wp_campaign_manager",
    code: "campaign_manager_profile",
    displayName: "Campaign Manager — Worker Profile",
    description: "Campaign management profile. Not yet active.",
    allowedExecutionChannels: ["internal_api", "document_store", "email_system"],
    allowedToolCategories: ["communication_tools", "reporting_tools", "calendar_tools"],
    allowedConnectorCategories: [],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: [],
    approvalRequiredActions: ["launch_campaign", "send_campaign_email"],
    riskLevel: "low",
    status: "coming_soon",
    version: "1.0.0",
  },
  {
    id: "wp_brand_manager",
    code: "brand_manager_profile",
    displayName: "Brand Manager — Worker Profile",
    description: "Brand identity profile. Not yet active.",
    allowedExecutionChannels: ["internal_api", "document_store"],
    allowedToolCategories: ["document_tools"],
    allowedConnectorCategories: [],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: [],
    approvalRequiredActions: ["update_brand_guidelines"],
    riskLevel: "low",
    status: "coming_soon",
    version: "1.0.0",
  },
  {
    id: "wp_social_media_specialist",
    code: "social_media_specialist_profile",
    displayName: "Social Media Specialist — Worker Profile",
    description: "Social media management profile. Not yet active.",
    allowedExecutionChannels: ["internal_api", "web_browser", "document_store"],
    allowedToolCategories: ["communication_tools", "search_tools"],
    allowedConnectorCategories: [],
    allowedBrowserDomains: [],
    allowedLocalPathCategories: [],
    allowedApplicationCategories: [],
    prohibitedActions: [],
    approvalRequiredActions: ["post_to_social_media"],
    riskLevel: "low",
    status: "coming_soon",
    version: "1.0.0",
  },
];

// ─── Mapping: Workforce Role code → Worker Profile code(s) ───────────────────
// Each Workforce Role (AI Specialist) is mapped to one or more Worker Profiles.
// This is the metadata relationship the spec requires.

export const ROLE_TO_PROFILES: Record<string, string[]> = {
  chief_of_staff:               ["chief_of_staff_profile"],
  executive_assistant:          ["executive_assistant_profile"],
  research_specialist:          ["research_specialist_profile"],
  document_specialist:          ["document_specialist_profile"],
  calendar_specialist:          ["calendar_specialist_profile"],
  communication_specialist:     ["communication_specialist_profile"],
  compliance_officer:           ["compliance_officer_profile"],
  compliance_quality_manager:   ["compliance_quality_manager_profile"],
  quality_officer:              ["quality_officer_profile"],
  policy_officer:               ["policy_officer_profile"],
  policy_governance_specialist: ["policy_governance_specialist_profile"],
  incident_review_officer:      ["incident_review_officer_profile"],
  incident_safeguarding_specialist: ["incident_safeguarding_specialist_profile"],
  corrective_action_officer:    ["corrective_action_officer_profile"],
  restrictive_practice_officer: ["restrictive_practice_officer_profile"],
  authorised_program_officer:    ["authorised_program_officer_profile"],
  behaviour_support_implementation_specialist: ["behaviour_support_implementation_specialist_profile"],
  operations_manager:           ["operations_manager_profile"],
  service_delivery_coordinator: ["service_delivery_coordinator_profile"],
  workforce_rostering_coordinator: ["workforce_rostering_coordinator_profile"],
  roster_coordinator:           ["roster_coordinator_profile"],
  asset_coordinator:            ["asset_coordinator_profile"],
  workflow_coordinator:         ["workflow_coordinator_profile"],
  process_asset_coordinator:    ["process_asset_coordinator_profile"],
  accounts_officer:             ["accounts_officer_profile"],
  finance_officer:              ["finance_officer_profile"],
  payroll_officer:              ["payroll_officer_profile"],
  payroll_workforce_cost_officer:["payroll_workforce_cost_officer_profile"],
  invoice_specialist:           ["invoice_specialist_profile"],
  budget_analyst:               ["budget_analyst_profile"],
  financial_reporting_officer:  ["financial_reporting_officer_profile"],
  financial_planning_reporting_manager: ["financial_planning_reporting_manager_profile"],
  people_culture_manager:       ["people_culture_manager_profile"],
  hr_officer:                   ["hr_officer_profile"],
  recruitment_officer:          ["recruitment_officer_profile"],
  learning_coordinator:         ["learning_coordinator_profile"],
  talent_learning_specialist:   ["talent_learning_specialist_profile"],
  performance_officer:          ["performance_officer_profile"],
  staff_compliance_officer:     ["staff_compliance_officer_profile"],
  workforce_compliance_specialist: ["workforce_compliance_specialist_profile"],
  marketing_director:           ["marketing_director_profile"],
  marketing_communications_manager: ["marketing_communications_manager_profile"],
  content_strategist:           ["content_strategist_profile"],
  campaign_manager:             ["campaign_manager_profile"],
  brand_manager:                ["brand_manager_profile"],
  social_media_specialist:      ["social_media_specialist_profile"],
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

export function getWorkerProfileByCode(code: string): WorkerProfile | undefined {
  return WORKER_PROFILES.find(p => p.code === code);
}

export function getWorkerProfilesForRole(workforceRoleCode: string): WorkerProfile[] {
  const codes = ROLE_TO_PROFILES[workforceRoleCode] ?? [];
  return codes
    .map(code => getWorkerProfileByCode(code))
    .filter((p): p is WorkerProfile => !!p);
}

export function getActiveWorkerProfilesForRole(workforceRoleCode: string): WorkerProfile[] {
  return getWorkerProfilesForRole(workforceRoleCode).filter(
    p => p.status === "active" || p.status === "beta"
  );
}

export function getRoleCodesForProfile(workerProfileCode: string): string[] {
  return Object.entries(ROLE_TO_PROFILES)
    .filter(([, profiles]) => profiles.includes(workerProfileCode))
    .map(([roleCode]) => roleCode);
}
