/**
 * knowledge_curation_jobs — Sprint 21
 *
 * Tracks Knowledge Curation Jobs created by the Chief of Staff when
 * Organisation Library documents are uploaded, approved, superseded, or archived.
 *
 * One job per document event.
 * Job status: pending → processing → completed | failed
 * Proposals generated by each job are stored in organisation_memory (sourceType="ai_proposed").
 *
 * Tenant isolation enforced by RLS on organization_id.
 */

import { pgTable, text, timestamp, integer, jsonb } from "drizzle-orm/pg-core";
import { organizationsTable }           from "./organizations.js";
import { knowledgeSourcesTable }        from "./knowledgeSources.js";

export const knowledgeCurationJobsTable = pgTable("knowledge_curation_jobs", {
  id:               text("id").primaryKey(),
  organizationId:   text("organization_id").notNull()
                      .references(() => organizationsTable.id, { onDelete: "cascade" }),

  knowledgeSourceId: text("knowledge_source_id").notNull()
                       .references(() => knowledgeSourcesTable.id, { onDelete: "cascade" }),

  /** The version processed by this job */
  sourceVersionId:  text("source_version_id"),

  /**
   * Previous version ID — populated for version_changed jobs so the curator
   * can diff old vs new content and produce a Version Intelligence summary.
   */
  previousVersionId: text("previous_version_id"),

  /**
   * The document lifecycle event that triggered this job.
   * uploaded | approved | superseded | archived | version_changed
   */
  triggerEvent:     text("trigger_event").notNull(),

  /**
   * Job lifecycle.
   * pending → processing → completed | failed
   */
  status:           text("status").notNull().default("pending"),

  /** Number of memory proposals successfully created by this job */
  proposalsGenerated: integer("proposals_generated").notNull().default(0),

  /** Number of proposals that have since been approved by a human */
  proposalsAccepted:  integer("proposals_accepted").notNull().default(0),

  /**
   * Version Intelligence summary — populated for version_changed jobs.
   * Shape: VersionSummary (see knowledgeCurationService.ts)
   */
  versionSummary:   jsonb("version_summary"),

  /** Step-by-step processing log for debugging */
  processingLog:    jsonb("processing_log"),

  /** Error detail when status = "failed" */
  errorMessage:     text("error_message"),

  createdAt:        timestamp("created_at",   { withTimezone: true }).notNull().defaultNow(),
  completedAt:      timestamp("completed_at", { withTimezone: true }),
});

export type KnowledgeCurationJob       = typeof knowledgeCurationJobsTable.$inferSelect;
export type InsertKnowledgeCurationJob = typeof knowledgeCurationJobsTable.$inferInsert;
